/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unicorn.service.pantallas;

import unicorn.controller.*;
import unicorn.exceptions.*;
import unicorn.model.*;


import javax.swing.*;
import java.awt.*;
/**
 * @author KNOW-RIC
 */
public class I_LOGIN extends javax.swing.JFrame {
    private final AccountController accountController;

    /**
     * Creates new form OGIN
     */
    public I_LOGIN() {
        // Inicialización del controlador de cuentas
        AccountController tempController;
        try {
            // Usa el constructor completo si tu sistema lo requiere (ajusta según tus dependencias)
            tempController = new AccountController(
                new FileHandler<>(new Account()),
                new FileHandler<>(new Substitute()),
                new NewsController(new FileHandler<>(new News()), "admin"),
                new FileHandler<>(new FaQ())
            );
        } catch (AccountException | NewsException e) {
            JOptionPane.showMessageDialog(
                null,
                "Error al inicializar el sistema de cuentas:\n" + e.getMessage(),
                "Error crítico",
                JOptionPane.ERROR_MESSAGE
            );
            tempController = null;
            System.exit(1);
        }
        this.accountController = tempController;

        // Configuración del icono de la ventana
        Toolkit t = Toolkit.getDefaultToolkit();
        java.net.URL iconUrl = getClass().getResource("/unicorn/resources/resources/ICONO.png");
        if (iconUrl == null) {
            JOptionPane.showMessageDialog(
                null,
                "No se encontró /ICONO.png en el classpath",
                "Error de recursos",
                JOptionPane.ERROR_MESSAGE
            );
        } else {
            setIconImage(t.getImage(iconUrl));
        }

        // Inicialización de componentes gráficos
        initComponents();
        this.setSize(450, 600);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("CURSIVE");
        setupPlaceholders();
    }

    private void setupPlaceholders() {
        // Add focus listeners for placeholder behavior
        CMP_USERNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (CMP_USERNAME.getText().equals("Ingrese su nombre de usuario")) {
                    CMP_USERNAME.setText("");
                    CMP_USERNAME.setForeground(new java.awt.Color(255, 255, 255));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (CMP_USERNAME.getText().isEmpty()) {
                    CMP_USERNAME.setText("Ingrese su nombre de usuario");
                    CMP_USERNAME.setForeground(new java.awt.Color(102, 102, 102));
                }
            }
        });

        CMP_PASSWORD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (String.valueOf(CMP_PASSWORD.getPassword()).equals("Ingrese su contraseña")) {
                    CMP_PASSWORD.setText("");
                    CMP_PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (String.valueOf(CMP_PASSWORD.getPassword()).isEmpty()) {
                    CMP_PASSWORD.setText("Ingrese su contraseña");
                    CMP_PASSWORD.setForeground(new java.awt.Color(102, 102, 102));
                }
            }
        });

        CMP_USERNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    BTN_LOGINActionPerformed(null); // Ejecutar acción del botón de login
                }
            }
        });

        CMP_PASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    BTN_LOGINActionPerformed(null); // Ejecutar acción del botón de login
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        CMP_USERNAME = new javax.swing.JTextField();
        LIN_USERNAME = new javax.swing.JSeparator();
        CMP_PASSWORD = new javax.swing.JPasswordField();
        LIN_PASSWORD = new javax.swing.JSeparator();
        BTN_LOGIN = new javax.swing.JButton();
        BTN_RECOVERY = new javax.swing.JButton();
        SUBTITULO = new javax.swing.JLabel();
        BTN_REGISTER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 600));
        setMinimumSize(new java.awt.Dimension(450, 600));
        setName("I_LOGIN"); // NOI18N
        setSize(new java.awt.Dimension(450, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(10, 15, 34));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setBackground(new java.awt.Color(255, 255, 255));
        TITULO.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("INICIAR SESION");
        TITULO.setFocusable(false);
        TITULO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TITULO.setMaximumSize(new java.awt.Dimension(90, 16));
        TITULO.setMinimumSize(new java.awt.Dimension(90, 16));
        TITULO.setName(""); // NOI18N
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 190, 35));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicorn/resources/resources/LOGO1 (1)_1.jpg"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 180));

        CMP_USERNAME.setBackground(new java.awt.Color(10, 15, 34));
        CMP_USERNAME.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CMP_USERNAME.setForeground(new java.awt.Color(255, 255, 255));
        CMP_USERNAME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CMP_USERNAME.setText("Ingrese su nombre de usuario");
        CMP_USERNAME.setToolTipText("");
        CMP_USERNAME.setBorder(null);
        CMP_USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMP_USERNAMEActionPerformed(evt);
            }
        });
        jPanel1.add(CMP_USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 260, 30));

        LIN_USERNAME.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LIN_USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 260, 10));

        CMP_PASSWORD.setBackground(new java.awt.Color(10, 15, 34));
        CMP_PASSWORD.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CMP_PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        CMP_PASSWORD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CMP_PASSWORD.setText("Ingrese su contraseña");
        CMP_PASSWORD.setToolTipText("");
        CMP_PASSWORD.setActionCommand("<Not Set>");
        CMP_PASSWORD.setBorder(null);
        CMP_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMP_PASSWORDActionPerformed(evt);
            }
        });
        jPanel1.add(CMP_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 260, 30));

        LIN_PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LIN_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 260, 10));

        BTN_LOGIN.setBackground(new java.awt.Color(86, 178, 187));
        BTN_LOGIN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTN_LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        BTN_LOGIN.setText("INGRESAR");
        BTN_LOGIN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTN_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGINActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 173, 39));

        BTN_RECOVERY.setBackground(new java.awt.Color(10, 15, 34));
        BTN_RECOVERY.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BTN_RECOVERY.setForeground(new java.awt.Color(86, 178, 187));
        BTN_RECOVERY.setText("¿Olvidaste tu contraseña?");
        BTN_RECOVERY.setBorder(null);
        BTN_RECOVERY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RECOVERYActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_RECOVERY, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        SUBTITULO.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SUBTITULO.setForeground(new java.awt.Color(186, 199, 204));
        SUBTITULO.setText("¿Aun no tienes cuenta?");
        jPanel1.add(SUBTITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        BTN_REGISTER.setBackground(new java.awt.Color(10, 15, 34));
        BTN_REGISTER.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BTN_REGISTER.setForeground(new java.awt.Color(86, 178, 187));
        BTN_REGISTER.setText(" Crear una cuenta");
        BTN_REGISTER.setBorder(null);
        BTN_REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTERActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_REGISTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGINActionPerformed
        String username = CMP_USERNAME.getText().trim();
        String password = new String(CMP_PASSWORD.getPassword()).trim();

        // Validación de campos vacíos
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Account loggedAccount = accountController.login(username, password);

            // PASO 3: Forzar cambio de contraseña si es temporal
            if (loggedAccount.isRequiereCambioPassword()) {
                boolean changed = false;
                while (!changed) {
                    JPanel panel = new JPanel(new GridLayout(3, 2, 5, 5));
                    JLabel lbl1 = new JLabel("Nueva contraseña:");
                    JPasswordField pf1 = new JPasswordField();
                    JLabel lbl2 = new JLabel("Confirmar contraseña:");
                    JPasswordField pf2 = new JPasswordField();
                    JLabel lblError = new JLabel(" ");
                    lblError.setForeground(Color.RED);

                    panel.add(lbl1); panel.add(pf1);
                    panel.add(lbl2); panel.add(pf2);
                    panel.add(lblError);

                    int result = JOptionPane.showConfirmDialog(
                        this, panel, "Cambio de Contraseña Requerido",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE
                    );

                    if (result != JOptionPane.OK_OPTION) {
                        // Si cancela, no deja entrar
                        return;
                    }

                    String nueva = new String(pf1.getPassword()).trim();
                    String confirmar = new String(pf2.getPassword()).trim();

                    if (nueva.isEmpty() || confirmar.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No puede dejar campos vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
                        continue;
                    }
                    if (!nueva.equals(confirmar)) {
                        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
                        continue;
                    }
                    if (nueva.length() < 8) {
                        JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
                        continue;
                    }

                    // Cambia la contraseña y quita el flag
                    loggedAccount.setPassword(nueva);
                    loggedAccount.setRequiereCambioPassword(false);
                    accountController.saveChanges();
                    JOptionPane.showMessageDialog(this, "Contraseña cambiada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    changed = true;
                }
            }

            // Redirigir según el tipo de cuenta
            switch (loggedAccount.getTipoCuenta()) {
                case ADMIN:
                    new VI_ADM_BNV(loggedAccount).setVisible(true);
                    break;
                case PROFESOR:
                    new V_PRF_BNV(loggedAccount).setVisible(true);
                    break;
                case ESTUDIANTE:
                    new IV_EST_BNV(loggedAccount).setVisible(true);
                    break;
            }
            
            this.dispose(); // Cerrar la ventana de login
        } catch (AccountException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTN_LOGINActionPerformed

    private void CMP_USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMP_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMP_USERNAMEActionPerformed

    private void CMP_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMP_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMP_PASSWORDActionPerformed

    private void BTN_RECOVERYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RECOVERYActionPerformed
        I_RECOVER recoveryScreen = new I_RECOVER(accountController);
        recoveryScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_RECOVERYActionPerformed

    private void BTN_REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTERActionPerformed
        I_REGISTER registerScreen = new I_REGISTER(accountController);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_REGISTERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new I_LOGIN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_LOGIN;
    private javax.swing.JButton BTN_RECOVERY;
    private javax.swing.JButton BTN_REGISTER;
    private javax.swing.JPasswordField CMP_PASSWORD;
    private javax.swing.JTextField CMP_USERNAME;
    private javax.swing.JSeparator LIN_PASSWORD;
    private javax.swing.JSeparator LIN_USERNAME;
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel SUBTITULO;
    private javax.swing.JLabel TITULO;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
