/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unicorn.service.pantallas;

import unicorn.controller.*;
import unicorn.exceptions.*;
import unicorn.model.*;


import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 * @author KNOW-RIC
 */
public class IV_EST_FAQ extends javax.swing.JFrame {
    private final Account account;
    private final FaQController faqController;

    /**
     * Creates new form DOCENTE
     * @param account
     */
    public IV_EST_FAQ(Account account) {
        FaQController tempController;
        try {
            tempController = new FaQController(new FileHandler<>(new FaQ()));
        } catch (FaQException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.faqController = tempController;
        this.account = account;
        initComponents();
        setTitle("CURSIVE - Panel de Estudiante");
        setSize(1360, 800);
        setLocationRelativeTo(null);
        setResizable(false);
   
        // Configuración del icono de la ventana
        Toolkit t = Toolkit.getDefaultToolkit();
        java.net.URL iconUrl = getClass().getResource("/unicorn/resources/resources/ICONO.png");
        if (iconUrl == null) {
            JOptionPane.showMessageDialog(
                null,
                "No se encontró /ICONO.png en el classpath",
                "Error de recursos",
                JOptionPane.ERROR_MESSAGE
            );
        } else {
            setIconImage(t.getImage(iconUrl));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FONDO = new javax.swing.JPanel();
        PNL_OPTION = new javax.swing.JPanel();
        BTN_MIHORARIO = new javax.swing.JButton();
        BTN_NOTIFICACIONES = new javax.swing.JButton();
        BTN_FaQ = new javax.swing.JButton();
        PNL_TOP = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        BIENVENIDA = new javax.swing.JLabel();
        BTN_MYACC = new javax.swing.JButton();
        BTN_LOGOUT = new javax.swing.JButton();
        BTN_RAIZ = new javax.swing.JButton();
        SUBTITULO = new javax.swing.JLabel();
        CMP_QUESTION = new javax.swing.JTextArea();
        BTN_ALL_FAQ = new javax.swing.JButton();
        BTN_NEW_FAQ = new javax.swing.JButton();
        BTN_ACCESO = new javax.swing.JButton();
        BTN_DESARROLADORES = new javax.swing.JButton();
        BTN_CONTACTO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 800));
        setName("EST"); // NOI18N
        setSize(new java.awt.Dimension(1360, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FONDO.setBackground(new java.awt.Color(77, 199, 183));
        FONDO.setMaximumSize(new java.awt.Dimension(1360, 800));
        FONDO.setMinimumSize(new java.awt.Dimension(1360, 800));
        FONDO.setPreferredSize(new java.awt.Dimension(1360, 800));
        FONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PNL_OPTION.setBackground(new java.awt.Color(10, 15, 34));
        PNL_OPTION.setPreferredSize(new java.awt.Dimension(260, 800));
        PNL_OPTION.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_MIHORARIO.setBackground(new java.awt.Color(32, 97, 96));
        BTN_MIHORARIO.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_MIHORARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTN_MIHORARIO.setText("MI HORARIO");
        BTN_MIHORARIO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTN_MIHORARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MIHORARIOActionPerformed(evt);
            }
        });
        PNL_OPTION.add(BTN_MIHORARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, 60));

        BTN_NOTIFICACIONES.setBackground(new java.awt.Color(32, 97, 96));
        BTN_NOTIFICACIONES.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_NOTIFICACIONES.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NOTIFICACIONES.setText("NOTIFICACION");
        BTN_NOTIFICACIONES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTN_NOTIFICACIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NOTIFICACIONESActionPerformed(evt);
            }
        });
        PNL_OPTION.add(BTN_NOTIFICACIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 240, 60));

        BTN_FaQ.setBackground(new java.awt.Color(77, 199, 183));
        BTN_FaQ.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_FaQ.setForeground(new java.awt.Color(10, 15, 34));
        BTN_FaQ.setText("FAQ");
        BTN_FaQ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTN_FaQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FaQActionPerformed(evt);
            }
        });
        PNL_OPTION.add(BTN_FaQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 240, 50));

        FONDO.add(PNL_OPTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 690));

        PNL_TOP.setBackground(new java.awt.Color(10, 15, 34));

        TITULO.setFont(new java.awt.Font("Fira Code", 1, 48)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("CURSIVE");

        BIENVENIDA.setFont(new java.awt.Font("Fira Code", 1, 48)); // NOI18N
        BIENVENIDA.setForeground(new java.awt.Color(255, 255, 255));
        BIENVENIDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BIENVENIDA.setText("AYUDA Y SOPORTE");
        BIENVENIDA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BTN_MYACC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicorn/resources/resources/I_PERFIL.png"))); // NOI18N
        BTN_MYACC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MYACCActionPerformed(evt);
            }
        });

        BTN_LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicorn/resources/resources/LOGOUT.png"))); // NOI18N
        BTN_LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGOUTActionPerformed(evt);
            }
        });

        BTN_RAIZ.setBackground(new java.awt.Color(10, 15, 34));
        BTN_RAIZ.setForeground(new java.awt.Color(10, 15, 34));
        BTN_RAIZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicorn/resources/resources/I_ICON.png"))); // NOI18N
        BTN_RAIZ.setBorder(null);
        BTN_RAIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RAIZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_TOPLayout = new javax.swing.GroupLayout(PNL_TOP);
        PNL_TOP.setLayout(PNL_TOPLayout);
        PNL_TOPLayout.setHorizontalGroup(
            PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_TOPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_RAIZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(BIENVENIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(BTN_MYACC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PNL_TOPLayout.setVerticalGroup(
            PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TOPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTN_RAIZ)
                    .addGroup(PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_MYACC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PNL_TOPLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(TITULO)))
                    .addGroup(PNL_TOPLayout.createSequentialGroup()
                        .addComponent(BIENVENIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FONDO.add(PNL_TOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 110));

        SUBTITULO.setFont(new java.awt.Font("Fira Code", 1, 48)); // NOI18N
        SUBTITULO.setForeground(new java.awt.Color(10, 15, 34));
        SUBTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SUBTITULO.setText("INGRESE SU PREGUNTA");
        SUBTITULO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FONDO.add(SUBTITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        CMP_QUESTION = new javax.swing.JTextArea();
        CMP_QUESTION.setLineWrap(true);
        CMP_QUESTION.setWrapStyleWord(true);
        CMP_QUESTION.setFont(new java.awt.Font("Fira Code", 0, 18));
        JScrollPane scrollPane = new JScrollPane(CMP_QUESTION);
        FONDO.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 700, 170));

        BTN_ALL_FAQ.setBackground(new java.awt.Color(32, 97, 96));
        BTN_ALL_FAQ.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_ALL_FAQ.setForeground(new java.awt.Color(10, 15, 34));
        BTN_ALL_FAQ.setText("VER TODO");
        BTN_ALL_FAQ.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_ALL_FAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ALL_FAQActionPerformed(evt);
            }
        });
        FONDO.add(BTN_ALL_FAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, 250, 40));

        BTN_NEW_FAQ.setBackground(new java.awt.Color(32, 97, 96));
        BTN_NEW_FAQ.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_NEW_FAQ.setForeground(new java.awt.Color(10, 15, 34));
        BTN_NEW_FAQ.setText("ENVIAR");
        BTN_NEW_FAQ.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_NEW_FAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NEW_FAQActionPerformed(evt);
            }
        });
        FONDO.add(BTN_NEW_FAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 250, 40));

        BTN_ACCESO.setBackground(new java.awt.Color(32, 97, 96));
        BTN_ACCESO.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_ACCESO.setForeground(new java.awt.Color(10, 15, 34));
        BTN_ACCESO.setText("ACCESO");
        BTN_ACCESO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_ACCESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACCESOActionPerformed(evt);
            }
        });
        FONDO.add(BTN_ACCESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 690, 250, 40));

        BTN_DESARROLADORES.setBackground(new java.awt.Color(32, 97, 96));
        BTN_DESARROLADORES.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_DESARROLADORES.setForeground(new java.awt.Color(10, 15, 34));
        BTN_DESARROLADORES.setText("DESARROLADORES");
        BTN_DESARROLADORES.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_DESARROLADORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DESARROLADORESActionPerformed(evt);
            }
        });
        FONDO.add(BTN_DESARROLADORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 690, 250, 40));

        BTN_CONTACTO.setBackground(new java.awt.Color(32, 97, 96));
        BTN_CONTACTO.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_CONTACTO.setForeground(new java.awt.Color(10, 15, 34));
        BTN_CONTACTO.setText("CONTACTO");
        BTN_CONTACTO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_CONTACTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CONTACTOActionPerformed(evt);
            }
        });
        FONDO.add(BTN_CONTACTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 690, 250, 40));

        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_MIHORARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MIHORARIOActionPerformed
        IV_EST_HORARIO registerScreen = new IV_EST_HORARIO(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_MIHORARIOActionPerformed

    private void BTN_NOTIFICACIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NOTIFICACIONESActionPerformed
        V_PRF_NOTIFICACIONES registerScreen = new V_PRF_NOTIFICACIONES(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_NOTIFICACIONESActionPerformed

    private void BTN_MYACCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MYACCActionPerformed
        I_MYACC registerScreen = new I_MYACC(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_MYACCActionPerformed

    private void BTN_FaQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FaQActionPerformed
        IV_EST_FAQ registerScreen = new IV_EST_FAQ(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_FaQActionPerformed

    private void BTN_LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGOUTActionPerformed
        I_LOGIN registerScreen = new I_LOGIN();
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_LOGOUTActionPerformed

    private void BTN_CONTACTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CONTACTOActionPerformed
        // Crear un panel personalizado para el JOptionPane
        JPanel contactPanel = new JPanel();
        contactPanel.setLayout(new BoxLayout(contactPanel, BoxLayout.Y_AXIS));
        contactPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Estilo para los textos
        Font titleFont = new Font("Times New Roman", Font.BOLD, 18);
        Font infoFont = new Font("Times New Roman", Font.PLAIN, 16);

        // Título
        JLabel titleLabel = new JLabel("Información de Contacto");
        titleLabel.setFont(titleFont);
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Teléfono
        JLabel phoneLabel = new JLabel("Teléfono: +591 65385455");
        phoneLabel.setFont(infoFont);
        phoneLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Email
        JLabel emailLabel = new JLabel("Email: 202400347@est.umss.edu");
        emailLabel.setFont(infoFont);
        emailLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Agregar componentes al panel
        contactPanel.add(titleLabel);
        contactPanel.add(Box.createRigidArea(new Dimension(0, 15)));
        contactPanel.add(phoneLabel);
        contactPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        contactPanel.add(emailLabel);

        // Mostrar el JOptionPane con el panel personalizado
        JOptionPane.showMessageDialog(
            this,
            contactPanel,
            "Contacto",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_BTN_CONTACTOActionPerformed

    private void BTN_RAIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RAIZActionPerformed
        switch (account.getTipoCuenta()) {
            case ADMIN -> new VI_ADM_BNV(account).setVisible(true);
            case PROFESOR -> new V_PRF_BNV(account).setVisible(true);
            case ESTUDIANTE -> new IV_EST_BNV(account).setVisible(true);
        }
    }//GEN-LAST:event_BTN_RAIZActionPerformed

    private void BTN_ACCESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACCESOActionPerformed
        System.out.println("BOTÓN ACCESO PRESIONADO");

        if (!Desktop.isDesktopSupported()) {
            JOptionPane.showMessageDialog(this,
                "Tu sistema no soporta esta acción",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String url = "https://maps.app.goo.gl/FgMJs7MVMYv9FcgB6";
            
            // Usamos xdg-open que funciona en la mayoría de entornos Linux con GUI
            Runtime.getRuntime().exec(new String[]{"xdg-open", url});
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                "Error al abrir el mapa: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTN_ACCESOActionPerformed

    private void BTN_DESARROLADORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DESARROLADORESActionPerformed
        I_DESARROLLADORES registerScreen = new I_DESARROLLADORES(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_DESARROLADORESActionPerformed

    private void CMP_QUESTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMP_QUESTIONActionPerformed
        // add your handling code here:
    }//GEN-LAST:event_CMP_QUESTIONActionPerformed

    private void BTN_ALL_FAQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ALL_FAQActionPerformed
        IV_EST_FAQ_ALL registerScreen = new IV_EST_FAQ_ALL(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_ALL_FAQActionPerformed

    private void BTN_NEW_FAQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NEW_FAQActionPerformed
         // Get the question from the text field
         System.out.println("CLICK ENVIAR");
        String pregunta = CMP_QUESTION.getText().trim();
        System.out.println("Pregunta: " + pregunta);
        
        // Validate if the question is not empty
        if (pregunta.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor ingrese su pregunta",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Create a new FAQ with pending status
            FaQ newFaq = new FaQ(pregunta);
            
            // Add the FAQ to the system
            faqController.addFaq(newFaq);
            
            // Show success message with tracking ID
            JOptionPane.showMessageDialog(this,
                "Pregunta enviada exitosamente.\nID de seguimiento: " + newFaq.getId(),
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Clear the question field
            CMP_QUESTION.setText("");
            
        } catch (FaQException e) {
            JOptionPane.showMessageDialog(this,
                "Error al enviar la pregunta: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTN_NEW_FAQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IV_EST_FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IV_EST_FAQ(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BIENVENIDA;
    private javax.swing.JButton BTN_ACCESO;
    private javax.swing.JButton BTN_ALL_FAQ;
    private javax.swing.JButton BTN_CONTACTO;
    private javax.swing.JButton BTN_DESARROLADORES;
    private javax.swing.JButton BTN_FaQ;
    private javax.swing.JButton BTN_LOGOUT;
    private javax.swing.JButton BTN_MIHORARIO;
    private javax.swing.JButton BTN_MYACC;
    private javax.swing.JButton BTN_NEW_FAQ;
    private javax.swing.JButton BTN_NOTIFICACIONES;
    private javax.swing.JButton BTN_RAIZ;
    private javax.swing.JTextArea CMP_QUESTION;
    private javax.swing.JPanel FONDO;
    private javax.swing.JPanel PNL_OPTION;
    private javax.swing.JPanel PNL_TOP;
    private javax.swing.JLabel SUBTITULO;
    private javax.swing.JLabel TITULO;
    // End of variables declaration//GEN-END:variables
}
