/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unicorn.service.pantallas;

import unicorn.controller.*;
import unicorn.exceptions.*;
import unicorn.model.*;


import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import java.awt.*;
import java.util.List;

/**
 * @author KNOW-RIC
 */
public class VI_ADM_FAQ_ALL extends javax.swing.JFrame {
    private final Account account;
    private final FaQController faqController;

    /**
     * Creates new form DOCENTE
     * @param account
     */
    public VI_ADM_FAQ_ALL(Account account) {
        FaQController tempController;
        try {
            tempController = new FaQController(new FileHandler<>(new FaQ()));
        } catch (FaQException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.faqController = tempController;
        this.account = account;
        initComponents();
        setTitle("CURSIVE - Panel de Estudiante");
        setSize(1360, 800);
        setLocationRelativeTo(null);
        setResizable(false);
   
        // Configuración del icono de la ventana
        Toolkit t = Toolkit.getDefaultToolkit();
        java.net.URL iconUrl = getClass().getResource("/unicorn/resources/resources/ICONO.png");
        if (iconUrl == null) {
            JOptionPane.showMessageDialog(
                null,
                "No se encontró /ICONO.png en el classpath",
                "Error de recursos",
                JOptionPane.ERROR_MESSAGE
            );
        } else {
            setIconImage(t.getImage(iconUrl));
        }
        
        loadFaQsToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FONDO = new javax.swing.JPanel();
        PNL_OPTION = new javax.swing.JPanel();
        BTN_MIHORARIO = new javax.swing.JButton();
        BTN_NOTIFICACIONES = new javax.swing.JButton();
        BTN_FaQ = new javax.swing.JButton();
        BTN_VOLVER = new javax.swing.JButton();
        PNL_TOP = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        BIENVENIDA = new javax.swing.JLabel();
        BTN_MYACC = new javax.swing.JButton();
        BTN_LOGOUT = new javax.swing.JButton();
        BTN_RAIZ = new javax.swing.JButton();
        TBL_ALL_FAQ = new javax.swing.JScrollPane();
        DTO_HISTORY = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 800));
        setName("EST"); // NOI18N
        setSize(new java.awt.Dimension(1360, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FONDO.setBackground(new java.awt.Color(77, 199, 183));
        FONDO.setMaximumSize(new java.awt.Dimension(1100, 800));
        FONDO.setMinimumSize(new java.awt.Dimension(1100, 800));
        FONDO.setPreferredSize(new java.awt.Dimension(1100, 800));
        FONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PNL_OPTION.setBackground(new java.awt.Color(10, 15, 34));
        PNL_OPTION.setPreferredSize(new java.awt.Dimension(260, 800));
        PNL_OPTION.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_MIHORARIO.setBackground(new java.awt.Color(32, 97, 96));
        BTN_MIHORARIO.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_MIHORARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTN_MIHORARIO.setText("MI HORARIO");
        BTN_MIHORARIO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTN_MIHORARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MIHORARIOActionPerformed(evt);
            }
        });
        PNL_OPTION.add(BTN_MIHORARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, 60));

        BTN_NOTIFICACIONES.setBackground(new java.awt.Color(32, 97, 96));
        BTN_NOTIFICACIONES.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_NOTIFICACIONES.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NOTIFICACIONES.setText("NOTIFICACION");
        BTN_NOTIFICACIONES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTN_NOTIFICACIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NOTIFICACIONESActionPerformed(evt);
            }
        });
        PNL_OPTION.add(BTN_NOTIFICACIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 240, 60));

        BTN_FaQ.setBackground(new java.awt.Color(77, 199, 183));
        BTN_FaQ.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_FaQ.setForeground(new java.awt.Color(10, 15, 34));
        BTN_FaQ.setText("FAQ");
        BTN_FaQ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTN_FaQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FaQActionPerformed(evt);
            }
        });
        PNL_OPTION.add(BTN_FaQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 240, 50));

        FONDO.add(PNL_OPTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 690));

        BTN_VOLVER.setBackground(new java.awt.Color(32, 97, 96));
        BTN_VOLVER.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        BTN_VOLVER.setForeground(new java.awt.Color(10, 15, 34));
        BTN_VOLVER.setText("VOLVER");
        BTN_VOLVER.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_VOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_VOLVERActionPerformed(evt);
            }
        });
        FONDO.add(BTN_VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 720, 250, 40));

        PNL_TOP.setBackground(new java.awt.Color(10, 15, 34));

        TITULO.setFont(new java.awt.Font("Fira Code", 1, 48)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("CURSIVE");

        BIENVENIDA.setFont(new java.awt.Font("Fira Code", 1, 48)); // NOI18N
        BIENVENIDA.setForeground(new java.awt.Color(255, 255, 255));
        BIENVENIDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BIENVENIDA.setText("AYUDA Y SOPORTE");
        BIENVENIDA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BTN_MYACC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicorn/resources/resources/I_PERFIL.png"))); // NOI18N
        BTN_MYACC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MYACCActionPerformed(evt);
            }
        });

        BTN_LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicorn/resources/resources/LOGOUT.png"))); // NOI18N
        BTN_LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGOUTActionPerformed(evt);
            }
        });

        BTN_RAIZ.setBackground(new java.awt.Color(10, 15, 34));
        BTN_RAIZ.setForeground(new java.awt.Color(10, 15, 34));
        BTN_RAIZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicorn/resources/resources/I_ICON.png"))); // NOI18N
        BTN_RAIZ.setBorder(null);
        BTN_RAIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RAIZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_TOPLayout = new javax.swing.GroupLayout(PNL_TOP);
        PNL_TOP.setLayout(PNL_TOPLayout);
        PNL_TOPLayout.setHorizontalGroup(
            PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_TOPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_RAIZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(BIENVENIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(BTN_MYACC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PNL_TOPLayout.setVerticalGroup(
            PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TOPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTN_RAIZ)
                    .addGroup(PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PNL_TOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_MYACC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PNL_TOPLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(TITULO)))
                    .addGroup(PNL_TOPLayout.createSequentialGroup()
                        .addComponent(BIENVENIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FONDO.add(PNL_TOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 110));

        DTO_HISTORY.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PREGUNTA", "RESPUESTA"
            }
        ));
        TBL_ALL_FAQ.setViewportView(DTO_HISTORY);

        FONDO.add(TBL_ALL_FAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 830, 410));

        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_MIHORARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MIHORARIOActionPerformed
        IV_EST_HORARIO registerScreen = new IV_EST_HORARIO(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_MIHORARIOActionPerformed

    private void BTN_NOTIFICACIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NOTIFICACIONESActionPerformed
        V_PRF_NOTIFICACIONES registerScreen = new V_PRF_NOTIFICACIONES(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_NOTIFICACIONESActionPerformed

    private void BTN_MYACCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MYACCActionPerformed
        I_MYACC registerScreen = new I_MYACC(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_MYACCActionPerformed

    private void BTN_FaQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FaQActionPerformed
        VI_ADM_FAQ_ALL registerScreen = new VI_ADM_FAQ_ALL(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_FaQActionPerformed

    private void BTN_LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGOUTActionPerformed
        I_LOGIN registerScreen = new I_LOGIN();
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_LOGOUTActionPerformed

    private void BTN_VOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VOLVERActionPerformed
        IV_EST_FAQ registerScreen = new IV_EST_FAQ(account);
        registerScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_VOLVERActionPerformed

    private void BTN_RAIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RAIZActionPerformed
        switch (account.getTipoCuenta()) {
            case ADMIN -> new VI_ADM_BNV(account).setVisible(true);
            case PROFESOR -> new V_PRF_BNV(account).setVisible(true);
            case ESTUDIANTE -> new IV_EST_BNV(account).setVisible(true);
        }
    }//GEN-LAST:event_BTN_RAIZActionPerformed

    private void loadFaQsToTable() {
        try {
            // Get the table model
            DefaultTableModel model = (DefaultTableModel) DTO_HISTORY.getModel();
            
            // Clear existing rows
            model.setRowCount(0);

            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            
            // Get all FAQs and add them to the table
            List<FaQ> faqs = faqController.getAllFaqs();
            for (FaQ faq : faqs) {
                String fecha = (faq.getFechaRespuesta() != null)
                    ? faq.getFechaRespuesta().format(formatter)
                    : "Pendiente";
                model.addRow(new Object[]{
                    faq.getPregunta(),
                    faq.getRespuesta(),
                    fecha,
                    faq.getResponderID() != null ? faq.getResponderID() : "Pendiente"
                });
            }
            
            // Cambiar fuente y tamaño de letra de la tabla
            DTO_HISTORY.setFont(new Font("Fira Code", Font.PLAIN, 18));
            DTO_HISTORY.getTableHeader().setFont(new Font("Fira Code", Font.BOLD, 20));

            // Renderer multilínea SOLO para pregunta y respuesta
            DTO_HISTORY.getColumnModel().getColumn(0).setCellRenderer(new MultiLineTableCellRenderer()); // Pregunta
            DTO_HISTORY.getColumnModel().getColumn(1).setCellRenderer(new MultiLineTableCellRenderer()); // Respuesta

            // Renderer centrado para fecha y usuario
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            DTO_HISTORY.getColumnModel().getColumn(2).setCellRenderer(centerRenderer); // Fecha
            DTO_HISTORY.getColumnModel().getColumn(3).setCellRenderer(centerRenderer); // Usuario

            // Ajusta el ancho de columnas si lo deseas
            DTO_HISTORY.getColumnModel().getColumn(0).setPreferredWidth(300);
            DTO_HISTORY.getColumnModel().getColumn(1).setPreferredWidth(300);
            DTO_HISTORY.getColumnModel().getColumn(2).setPreferredWidth(220);
            DTO_HISTORY.getColumnModel().getColumn(3).setPreferredWidth(120);
            
            // Set row height
            DTO_HISTORY.setRowHeight(40);
            DTO_HISTORY.setShowGrid(false); // Quita las líneas de la cuadrícula
            DTO_HISTORY.setIntercellSpacing(new java.awt.Dimension(0, 0)); // Sin espacio entre celdas
            
            /** Center align all columns
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < DTO_HISTORY.getColumnCount(); i++) {
                DTO_HISTORY.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }*/
            
        } catch (FaQException e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar las preguntas: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    class MultiLineTableCellRenderer extends JTextArea implements TableCellRenderer {
        public MultiLineTableCellRenderer() {
            setLineWrap(true);
            setWrapStyleWord(true);
            setFont(new Font("Fira Code", Font.PLAIN, 18));
            setOpaque(true);
        }
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value != null ? value.toString() : "");
            setSize(table.getColumnModel().getColumn(column).getWidth(), getPreferredSize().height);

            // Copia los colores de selección y fondo normales
            if (isSelected) {
                setBackground(table.getSelectionBackground());
                setForeground(table.getSelectionForeground());
            } else {
                setBackground(table.getBackground());
                setForeground(table.getForeground());
            }

            // Ajusta la altura de la fila para mostrar todo el texto
            int preferredHeight = getPreferredSize().height;
            if (table.getRowHeight(row) != preferredHeight) {
                table.setRowHeight(row, preferredHeight);
            }
            return this;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VI_ADM_FAQ_ALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VI_ADM_FAQ_ALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VI_ADM_FAQ_ALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VI_ADM_FAQ_ALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VI_ADM_FAQ_ALL(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BIENVENIDA;
    private javax.swing.JButton BTN_FaQ;
    private javax.swing.JButton BTN_LOGOUT;
    private javax.swing.JButton BTN_MIHORARIO;
    private javax.swing.JButton BTN_MYACC;
    private javax.swing.JButton BTN_NOTIFICACIONES;
    private javax.swing.JButton BTN_RAIZ;
    private javax.swing.JButton BTN_VOLVER;
    private javax.swing.JTable DTO_HISTORY;
    private javax.swing.JPanel FONDO;
    private javax.swing.JPanel PNL_OPTION;
    private javax.swing.JPanel PNL_TOP;
    private javax.swing.JScrollPane TBL_ALL_FAQ;
    private javax.swing.JLabel TITULO;
    // End of variables declaration//GEN-END:variables
}
